export type EmptyIllustration =
  | 'person-welcome'
  | 'person-search'
  | 'person-free-day'
  | 'person-first-materials'
  | 'person-unavailable'
  | 'person-success'
  | 'icon-search'
  | 'icon-free-week'
  | 'icon-unavailable'
  | 'icon-records'
  | 'icon-history'
  | 'icon-all-clear'
  | 'icon-import'
